#: import hex kivy.utils.get_color_from_hex
#: import dp kivy.metrics.dp

<CreateAccountScreen>:
    canvas.before:
        Color:
            rgb: hex(root.get_colors()["CREATE_ACCOUNT_SCREEN"]["BACKGROUND"]["MAIN"])
        Rectangle:
            size: self.size
            pos: self.pos
        

<WelcomeScreen>:
    canvas.before:
        Color:
            rgb: hex(root.get_colors()["WELCOME_SCREEN"]["BACKGROUND"]["MAIN"])
        Rectangle:
            size: self.size
            pos: self.pos
    Label:
        text: "Pendu"
        color: hex(root.get_colors()["WELCOME_SCREEN"]["TEXT"]["MAIN_LABEL"])
        size_hint: 0.7, 0.3
        font_size: min(self.width, self.height) * 0.25
        pos_hint: {"center_x":0.5, "center_y":0.90}

    BoxLayout:
        orientation: "vertical"
        size_hint: 0.75, 0.85
        pos_hint: {"center_x":0.45, "center_y":0.5}
        canvas.before:
            Color:
                rgb: hex(root.get_colors()["WELCOME_SCREEN"]["BACKGROUND"]["MAIN"])
            Rectangle:
                size: self.size
                pos: self.pos
                source: root.get_image_path("welcome_wood.png")
    BoxLayout:
        orientation: "vertical"
        size_hint: 0.45, 0.3
        pos_hint: {"center_x":0.7, "center_y":0.4}
        spacing: 40
        canvas.before:
            Color:
                rgb: hex(root.get_colors()["WELCOME_SCREEN"]["BACKGROUND"]["MAIN"])
            Rectangle:
                size: self.size
                pos: self.pos
        CustomButton:
            id: play_button
            text: "Jouer"
            size_hint: 1, 0.2
            
            bg_color: hex(root.get_colors()["WELCOME_SCREEN"]["BACKGROUND"]["MAIN_BUTTONS"]["ON_PRESS"])
            on_press: self.bg_color=hex(root.get_colors()["WELCOME_SCREEN"]["BACKGROUND"]["MAIN_BUTTONS"]["ON_RELEASE"])
            on_release: self.bg_color=hex(root.get_colors()["WELCOME_SCREEN"]["BACKGROUND"]["MAIN_BUTTONS"]["ON_PRESS"]); root.manager.current= "level_selecting_screen"; root.manager.transition.direction="left"#;root.check_tutorial_started()

        CustomButton:
            id: stat_button
            text: "Statistique"
            size_hint: 1, 0.2
            
            bg_color: hex(root.get_colors()["WELCOME_SCREEN"]["BACKGROUND"]["MAIN_BUTTONS"]["ON_PRESS"])
            on_press: self.bg_color=hex(root.get_colors()["WELCOME_SCREEN"]["BACKGROUND"]["MAIN_BUTTONS"]["ON_RELEASE"])
            on_release: self.bg_color=hex(root.get_colors()["WELCOME_SCREEN"]["BACKGROUND"]["MAIN_BUTTONS"]["ON_PRESS"]); root.manager.current= "stat_level_selecting"; root.manager.transition.direction="left"


        CustomButton:
            id: setting
            text: "Paramettre"
            size_hint: 1, 0.2
            
            bg_color: hex(root.get_colors()["WELCOME_SCREEN"]["BACKGROUND"]["MAIN_BUTTONS"]["ON_PRESS"])
            on_press: self.bg_color=hex(root.get_colors()["WELCOME_SCREEN"]["BACKGROUND"]["MAIN_BUTTONS"]["ON_RELEASE"])
            on_release: self.bg_color=hex(root.get_colors()["WELCOME_SCREEN"]["BACKGROUND"]["MAIN_BUTTONS"]["ON_PRESS"])

<LevelSelectingScreen>:
    canvas.before:
        Color:
            rgb: hex(root.get_colors()["LEVEL_SELECTING_SCREEN"]["BACKGROUND"]["MAIN"])
        Rectangle:
            size: self.size
            pos: self.pos
    CustomButton:
        id: exit
        text: "<<<"
        size_hint: 0.08, 0.08
        pos_hint: {"x":0.04, "y":0.88}
        font_size: min(self.width, self.height) * 0.32

        radius: [15]
        bg_color: hex(root.get_colors()["LEVEL_SELECTING_SCREEN"]["BACKGROUND"]["EXIT_BUTTON"]["ON_PRESS"])
        on_press: self.bg_color=hex(root.get_colors()["LEVEL_SELECTING_SCREEN"]["BACKGROUND"]["EXIT_BUTTON"]["ON_RELEASE"])
        on_release: self.bg_color=hex(root.get_colors()["LEVEL_SELECTING_SCREEN"]["BACKGROUND"]["EXIT_BUTTON"]["ON_PRESS"]); root.manager.current= "welcome_screen"; root.manager.transition.direction="right"
    FloatLayout:
        orientation: "vertical"
        size_hint: 1, 0.6
        pos_hint: {"center_x":0.5, "center_y":0.5}
        canvas.before:
            Color:
                rgb: hex(root.get_colors()["LEVEL_SELECTING_SCREEN"]["BACKGROUND"]["MAIN"])
            Rectangle:
                size: self.size
                pos: self.pos
                source: root.get_image_path("loggin_frame.png")
        BoxLayout:
            orientation: "vertical"
            size_hint: 0.45, 0.7
            pos_hint: {"center_x":0.46, "center_y":0.5}
            spacing: dp(15)
            padding: [15, 15, 15, 15]
            canvas.before:
                Color:
                    rgb: hex(root.get_colors()["LEVEL_SELECTING_SCREEN"]["BACKGROUND"]["MAIN"])#"#BCA77B")
                Rectangle:
                    size: self.size
                    pos: self.pos
            Label:
                text: "DIFFICULTE"
                font_size: min(self.width, self.height) * 0.20
                color: hex(root.get_colors()["LEVEL_SELECTING_SCREEN"]["TEXT"]["LABEL1"])
                bold: True
            BoxLayout:
                orientation: "vertical"
                BoxLayout:
                    orientation: "horizontal"
                    Label:
                        text: "Facile"
                        color: hex(root.get_colors()["LEVEL_SELECTING_SCREEN"]["TEXT"]["LABEL2"])
                        font_size: min(self.width, self.height) * 0.5
                        bold: True
                    CheckBox:
                        id: check_box1
                        group: "level"
                BoxLayout:
                    orientation: "horizontal"
                    Label:
                        text: "Corcé"
                        color: hex(root.get_colors()["LEVEL_SELECTING_SCREEN"]["TEXT"]["LABEL3"])
                        font_size: min(self.width, self.height) * 0.5
                        bold: True
                    CheckBox:
                        id: check_box2
                        group: "level"
                BoxLayout:
                    orientation: "horizontal"
                    Label:
                        text: "Infernal"
                        color: hex(root.get_colors()["LEVEL_SELECTING_SCREEN"]["TEXT"]["LABEL4"])
                        font_size: min(self.width, self.height) * 0.5
                        bold: True
                    CheckBox:
                        id: check_box3
                        group: "level"
            CustomButton:
                text: "COMMENCER"
                size_hint: 1, 0.5
                pos_hint: {"center_x":0.5, "center_y":0.5}
                font_size: min(self.width, self.height) * 0.25

                bg_color: hex(root.get_colors()["LEVEL_SELECTING_SCREEN"]["BACKGROUND"]["START_BUTTON"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["LEVEL_SELECTING_SCREEN"]["BACKGROUND"]["START_BUTTON"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["LEVEL_SELECTING_SCREEN"]["BACKGROUND"]["START_BUTTON"]["ON_PRESS"]); root.start_game()

<GameView>:

    displayer: displayer
    timer_displayer: timer_displayer
    buttons_container: buttons_container
    canvas.before:
        Color:
            rgb: hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["MAIN"])
        Rectangle:
            size: self.size
            pos: self.pos

    FloatLayout:
        orientation: "vertical"
        size_hint: 0.95, 0.45
        pos_hint: {"center_x":0.5, "center_y":0.76}
        canvas.before:
            Color:
                rgb: hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["MAIN"])
            Rectangle:
                size: self.size
                pos: self.pos
                source: root.get_image_path("game_info_frame.png")
        Label:
            id: word_len
            text:'0'
            size_hint: 0.3, 0.3
            pos_hint: {"center_x":0.865, "center_y":0.725}
            font_size: min(self.width, self.height) * 0.2

        Label:
            id: level_name
            text:''
            color: hex(root.get_colors()["GAME_VIEW"]["TEXT"]["LEVEL_TEXT"])
            pos_hint: {"x":0.05, "center_y":0.85}
            size_hint: 0.3, 0.3
            font_size: min(self.width, self.height) * 0.15
            bold: True

        BoxLayout:
            orientation: "vertical"
            size_hint: 0.2, 0.4
            pos_hint: {"center_x":0.85, "top":1}
            canvas.before:
                Rectangle:
                    size: self.size
                    pos: self.pos
                    source: root.get_image_path("rope.png")
        BoxLayout:
            id: buttons_container
            orientation: "horizontal"
            size_hint: 0.85, 0.1
            pos_hint: {"center_x":0.5, "center_y":0.5}
            spacing: 5
        BoxLayout:
            id: feathers_container
            orientation:'horizontal'
            size_hint: 0.70, 0.1
            pos_hint: {"center_x":0.43, "center_y":0.70}
            spacing: 5
            FeatherFrame:
                bg_color: hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["FEATHERS_FRAME"])
                image_path: root.get_image_path("f1.png")
            FeatherFrame:
                bg_color: hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["FEATHERS_FRAME"])
                image_path: root.get_image_path("f2.png")
            FeatherFrame:
                bg_color: hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["FEATHERS_FRAME"])
                image_path: root.get_image_path("f3.png")
            FeatherFrame:
                bg_color: hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["FEATHERS_FRAME"])
                image_path: root.get_image_path("f4.png")
            FeatherFrame:
                bg_color: hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["FEATHERS_FRAME"])
                image_path: root.get_image_path("f5.png")
            FeatherFrame:
                bg_color: hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["FEATHERS_FRAME"])
                image_path: root.get_image_path("f6.png")
            FeatherFrame:
                bg_color: hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["FEATHERS_FRAME"])
                image_path: root.get_image_path("f7.png")
            FeatherFrame:
                bg_color: hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["FEATHERS_FRAME"])
                image_path: root.get_image_path("f8.png")
            FeatherFrame:
                bg_color: hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["FEATHERS_FRAME"])
                image_path: root.get_image_path("f8.png")

        CustomTextInput:
            id: displayer
            size_hint: 0.5, 0.15
            pos_hint: {"center_x":0.5, "center_y":0.2}
            bg_color: hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["TEXTINPUT"]["ON_PRESS"])
            text_color: hex(root.get_colors()["GAME_VIEW"]["TEXT"]["TEXTINPUT"])
            readonly: True

        CustomButton:
            id: exit
            text: "<<<"
            size_hint: 0.08, 0.1
            pos_hint: {"x":0.05, "center_y":0.2}
            font_size: min(self.width, self.height) * 0.32
    
            radius: [15]
            bg_color: hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["EXIT_BUTTON"]["ON_PRESS"])
            on_press: self.bg_color=hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["EXIT_BUTTON"]["ON_RELEASE"])
            on_release: self.bg_color=hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["EXIT_BUTTON"]["ON_PRESS"]); root.number = root.default_number; root.ids.word_len.text = "0"; root.manager.current= "level_selecting_screen"; root.manager.transition.direction="right"; root.stop_timer = True; root.reset(is_reset_displayed_text=True, is_reset_life=True, is_reset_feather_cleaned_index=True, is_reset_letter_checked=True)

        Label:
            id: timer_displayer
            text: str(self.parent.parent.number)
            size_hint: 0.3, 0.3
            pos_hint: {"center_x":0.90, "center_y":0.2}
            font_size: min(self.width, self.height) * 0.2
            #color: hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["MAIN"])

    FloatLayout:
        id: event_displayer
        orientation:'horizontal'
        size_hint: 0.95, 0.11
        pos_hint: {"center_x":0.5, "center_y":0.45}
        canvas.before:
            Color:
                rgb: hex(root.get_colors()["GAME_VIEW"]["BACKGROUND"]["MAIN"])
            Rectangle:
                size: self.size
                pos: self.pos
        #Image:
        #    id: event_badge
        #    pos_hint: {"center_x":0.93, "center_y":0.5}
        #    size_hint: 0.35, 1
        #    source: ""

    CustomKeyBoard:
        id: keyboard
        target_input: displayer
        general_target: self.parent
        size_hint: 1, 0.35
        pos_hint: {"center_x":0.5, "center_y":0.2}

<StatLevelSelectingScreen>:
    canvas.before:
        Color:
            rgb: hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["BACKGROUND"]["MAIN"])
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        size_hint: 0.15, 0.3
        pos_hint: {"center_x":0.8, "top":1}
        canvas.before:
            Color:
                rgb: hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["BACKGROUND"]["MAIN"])
            Rectangle:
                size: self.size
                pos: self.pos
                source: root.get_image_path("rope.png")
    CustomButton:
        id: exit
        text: "<<<"
        size_hint: 0.08, 0.08
        pos_hint: {"x":0.04, "y":0.88}
        font_size: min(self.width, self.height) * 0.32

        radius: [15]
        bg_color: hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["BACKGROUND"]["EXIT_BUTTON"]["ON_PRESS"])
        on_press: self.bg_color=hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["BACKGROUND"]["EXIT_BUTTON"]["ON_RELEASE"])
        on_release: self.bg_color=hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["BACKGROUND"]["EXIT_BUTTON"]["ON_PRESS"]); root.manager.current= "welcome_screen"; root.manager.transition.direction="right"

    BoxLayout:
        orientation: "vertical"
        size_hint: 0.8, 0.4
        pos_hint: {"center_x":0.5, "center_y":0.5}
        spacing: dp(40)
        CustomButton:
            text: "INFERNAL"
            size_hint: 0.6, 0.2
            pos_hint: {"center_x":0.5, "center_y":0.5}
            color: hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["TEXT"]["MAIN_LABEL"])
            font_size: min(self.width, self.height) * 0.2

            bg_color: hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["BACKGROUND"]["MAIN_BUTTON"]["ON_PRESS"])
            on_press: self.bg_color=hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["BACKGROUND"]["MAIN_BUTTON"]["ON_RELEASE"])
            on_release: self.bg_color=hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["BACKGROUND"]["MAIN_BUTTON"]["ON_PRESS"]); root.update_player_level("hard"); root.manager.current= "player_data"
        CustomButton:
            text: "CORCE"
            size_hint: 0.8, 0.2
            pos_hint: {"center_x":0.5, "center_y":0.5}
            color: hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["TEXT"]["MAIN_LABEL"])
            font_size: min(self.width, self.height) * 0.2

            bg_color: hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["BACKGROUND"]["MAIN_BUTTON"]["ON_PRESS"])
            on_press: self.bg_color=hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["BACKGROUND"]["MAIN_BUTTON"]["ON_RELEASE"])
            on_release: self.bg_color=hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["BACKGROUND"]["MAIN_BUTTON"]["ON_PRESS"]); root.update_player_level("medium"); root.manager.current= "player_data"
        CustomButton:
            text: "FACILE"
            size_hint: 1, 0.2
            pos_hint: {"center_x":0.5, "center_y":0.5}
            color: hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["TEXT"]["MAIN_LABEL"])
            font_size: min(self.width, self.height) * 0.2

            bg_color: hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["BACKGROUND"]["MAIN_BUTTON"]["ON_PRESS"])
            on_press: self.bg_color=hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["BACKGROUND"]["MAIN_BUTTON"]["ON_RELEASE"])
            on_release: self.bg_color=hex(root.get_colors()["STAT_LEVEL_SELECTION_SCREEN"]["BACKGROUND"]["MAIN_BUTTON"]["ON_PRESS"]); root.update_player_level("noob"); root.manager.current= "player_data"

<DefeateScreen>:
    canvas.before:
        Color:
            rgb: hex(root.get_colors()["DEFEATE_SCREEN"]["BACKGROUND"]["MAIN"])
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        id: buttons_container2
        orientation: "horizontal"
        size_hint: 0.85, 0.08
        pos_hint: {"center_x":0.5, "center_y":0.93}
        spacing: 5

    BoxLayout:
        orientation:'horizontal'""
        size_hint: 0.85, 0.5
        pos_hint: {"center_x":0.5, "y":0.18}
        spacing: 5
        canvas.before:
            Color:
                rgb: hex(root.get_colors()["DEFEATE_SCREEN"]["BACKGROUND"]["MAIN"])
            Rectangle:
                size: self.size
                pos: self.pos
        BoxLayout:
            orientation:'vertical'
            padding: 2
            canvas.before:
                Color: 
                    rgb: hex(root.get_colors()["DEFEATE_SCREEN"]["BACKGROUND"]["BOX"]["COLOR1"])
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: [15]
            CustomTextInput:
                id: defintion_viewer
                size_hint: 1, 1
                pos_hint: {"center_x":0.5, "center_y":0.5}
                bg_color: hex(root.get_colors()["DEFEATE_SCREEN"]["BACKGROUND"]["BOX"]["COLOR2"])
                multiline: True
                default_value: 0.12
        BoxLayout:
            orientation:'vertical'
            padding: 2
            canvas.before:
                Color:
                    rgb: hex(root.get_colors()["DEFEATE_SCREEN"]["BACKGROUND"]["MAIN"])
                Rectangle:
                    size: self.size
                    pos: self.pos
            


    BoxLayout:
        orientation:'horizontal'
        size_hint: 0.8, 0.08
        pos_hint: {"center_x":0.5, "y":0.05}
        spacing: 10
        CustomButton:
            text: "CONTINUER"
            size_hint: 0.7, 1

            font_size: min(self.width, self.height) * 0.3
            bg_color: hex(root.get_colors()["DEFEATE_SCREEN"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
            on_press: self.bg_color=hex(root.get_colors()["DEFEATE_SCREEN"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
            on_release: self.bg_color=hex(root.get_colors()["DEFEATE_SCREEN"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
            bold: True
        CustomButton:
            text: "X"
            size_hint: 0.3, 1

            font_size: min(self.width, self.height) * 0.3
            bg_color: hex(root.get_colors()["DEFEATE_SCREEN"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
            on_press: self.bg_color=hex(root.get_colors()["DEFEATE_SCREEN"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
            on_release: self.bg_color=hex(root.get_colors()["DEFEATE_SCREEN"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); root.manager.current= "welcome_screen"
            bold: True

<VictoryScreen>:
    canvas.before:
        Color:
            rgb: hex(root.get_colors()["VICTORY_SCREEN"]["BACKGROUND"]["MAIN"])
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        id: buttons_container2
        orientation: "horizontal"
        size_hint: 0.85, 0.08
        pos_hint: {"center_x":0.5, "center_y":0.90}
        spacing: 5
    BoxLayout:
        orientation:'horizontal'""
        size_hint: 0.85, 0.5
        pos_hint: {"center_x":0.5, "y":0.18}
        spacing: 5
        canvas.before:
            Color:
                rgb: hex(root.get_colors()["VICTORY_SCREEN"]["BACKGROUND"]["MAIN"])
            Rectangle:
                size: self.size
                pos: self.pos
        BoxLayout:
            orientation:'vertical'
            padding: 2
            canvas.before:
                Color: 
                    rgb: hex(root.get_colors()["VICTORY_SCREEN"]["BACKGROUND"]["BOX"]["COLOR1"])
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: [15]
            CustomTextInput:
                id: defintion_viewer
                size_hint: 1, 1
                pos_hint: {"center_x":0.5, "center_y":0.5}
                bg_color: hex(root.get_colors()["VICTORY_SCREEN"]["BACKGROUND"]["BOX"]["COLOR2"])
                multiline: True
                default_value: 0.12
        BoxLayout:
            orientation:'vertical'
            padding: 2
            canvas.before:
                Color:
                    rgb: hex(root.get_colors()["VICTORY_SCREEN"]["BACKGROUND"]["MAIN"])
                Rectangle:
                    size: self.size
                    pos: self.pos
    BoxLayout:
        orientation:'horizontal'
        size_hint: 0.8, 0.08
        pos_hint: {"center_x":0.5, "y":0.05}
        spacing: 10
        CustomButton:
            text: "CONTINUER"
            size_hint: 0.7, 1

            font_size: min(self.width, self.height) * 0.3
            bg_color: hex(root.get_colors()["VICTORY_SCREEN"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
            on_press: self.bg_color=hex(root.get_colors()["VICTORY_SCREEN"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
            on_release: self.bg_color=hex(root.get_colors()["VICTORY_SCREEN"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); root.manager.current= "game_view"
            bold: True
        CustomButton:
            text: "X"
            size_hint: 0.3, 1
            
            font_size: min(self.width, self.height) * 0.3
            bg_color: hex(root.get_colors()["VICTORY_SCREEN"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
            on_press: self.bg_color=hex(root.get_colors()["VICTORY_SCREEN"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
            on_release: self.bg_color=hex(root.get_colors()["VICTORY_SCREEN"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); root.pass_menu; root.manager.current= "welcome_screen"
            bold: True


<PlayerDataScreen>:
    canvas.before:
        Color:
            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["MAIN"])
        Rectangle:
            size: self.size
            pos: self.pos

    CustomButton:
        id: exit
        text: "<<<"
        size_hint: 0.08, 0.08
        pos_hint: {"x":0.04, "y":0.88}
        font_size: min(self.width, self.height) * 0.32

        radius: [15]
        bg_color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["EXIT_BUTTON"]["ON_PRESS"])
        on_press: self.bg_color=hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["EXIT_BUTTON"]["ON_RELEASE"])
        on_release: self.bg_color=hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["EXIT_BUTTON"]["ON_PRESS"]); root.manager.current= "stat_level_selecting"; root.manager.transition.direction="right"
    BoxLayout:
        size_hint: 0.6, 0.25
        pos_hint: {"center_x":0.5, "top":1}
        canvas.before:
            Color:
                rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["MAIN"])
            Rectangle:
                size: self.size
                pos: self.pos
                source: root.get_image_path("title.png")

    BoxLayout:
        size_hint: 0.9, 0.7
        pos_hint: {"center_x":0.5, "center_y":0.38}
        canvas.before:
            Color:
                rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX1"])
            RoundedRectangle:
                size: self.size
                pos: self.pos
                radius: [dp(10), dp(10), dp(10), dp(10)]
        padding: [3, 3, 3, 3]
        BoxLayout:
            size_hint: 1, 1
            pos_hint: {"center_x":0.5, "center_y":0.5}
            canvas.before:
                Color:
                    rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX2"])
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: [dp(10), dp(10), dp(10), dp(10)]
            padding: [4, 8, 4, 8]
            BoxLayout:
                size_hint: 1, 1
                pos_hint: {"center_x":0.5, "center_y":0.5}
                canvas.before:
                    Color:
                        rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX3"])
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [dp(10), dp(10), dp(10), dp(10)]
                padding: [3, 3, 3, 3]
                BoxLayout:
                    size_hint: 1, 1
                    pos_hint: {"center_x":0.5, "center_y":0.5}
                    canvas.before:
                        Color:
                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX4"])
                        RoundedRectangle:
                            size: self.size
                            pos: self.pos
                            radius: [dp(10), dp(10), dp(10), dp(10)]
                    padding: [4, 8, 4, 8]
                    BoxLayout:
                        size_hint: 1, 1
                        pos_hint: {"center_x":0.5, "center_y":0.5}
                        canvas.before:
                            Color:
                                rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX5"])
                            RoundedRectangle:
                                size: self.size
                                pos: self.pos
                                radius: [dp(15), dp(15), dp(15), dp(15)]
                        padding: [4, 4, 4, 4]
                        ScrollView:
                            do_scroll_x: False

                            BoxLayout:
                                orientation: 'vertical'
                                pos_hint: {"center_x":0.5, "center_y":0.5}
                                canvas.before:
                                    Color:
                                        rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                    RoundedRectangle:
                                        size: self.size
                                        pos: self.pos
                                        radius: [dp(15), dp(15), dp(15), dp(15)]
                                size_hint_y: None
                                height: self.minimum_height
                                padding: [5, 5, 5, 5]
                                spacing: 10
                                Label:
                                    id: level_label
                                    text: ""
                                    size_hint_y: None
                                    height: 30
                                    pos_hint: {"center_x":0.5, "center_y":0.5}
                                    font_size: min(self.width, self.height) * 0.5
                                    color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR1"])
                                    bold: True
                                BoxLayout:
                                    orientation:'horizontal'
                                    size_hint_y: None
                                    height: self.minimum_height
                                    id: "frame1"
                                    canvas.before:
                                        Color:
                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                        Rectangle:
                                            size: self.size
                                            pos: self.pos
                                    spacing: 10
                                    BoxLayout:
                                        orientation:'vertical'
                                        size_hint: 1, None
                                        canvas.before:
                                            Color:
                                                rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX7"])
                                            RoundedRectangle:
                                                size: self.size
                                                pos: self.pos
                                                radius: [dp(15), dp(15), dp(15), dp(15)]
                                        height: 40
                                        Label:
                                            text: "Points"
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR1"])
                                            font_size: min(self.parent.width/2, self.parent.height/2) * 0.5
                                        Label:
                                            id: user_points
                                            text: ""
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR1"])
                                            font_size: min(self.parent.width/2, self.parent.height/2) * 0.5
                                    BoxLayout:
                                        orientation:'vertical'
                                        size_hint: 1, None
                                        canvas.before:
                                            Color:
                                                rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX7"])
                                            RoundedRectangle:
                                                size: self.size
                                                pos: self.pos
                                                radius: [dp(15), dp(15), dp(15), dp(15)]
                                        height: 40
                                        Label:
                                            text: "Parties jouées"
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR1"])
                                            font_size: min(self.parent.width/2, self.parent.height/2) * 0.5
                                        Label:
                                            id: games_played
                                            text: ""
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR1"])
                                            font_size: min(self.parent.width/2, self.parent.height/2) * 0.5
                                BoxLayout:
                                    orientation:'horizontal'
                                    size_hint_y: None
                                    height: self.minimum_height
                                    id: "frame2"
                                    canvas.before:
                                        Color:
                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                        Rectangle:
                                            size: self.size
                                            pos: self.pos
                                    spacing: 10
                                    BoxLayout:
                                        orientation:'vertical'
                                        size_hint: 1, None
                                        canvas.before:
                                            Color:
                                                rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX7"])
                                            RoundedRectangle:
                                                size: self.size
                                                pos: self.pos
                                                radius: [dp(15), dp(15), dp(15), dp(15)]
                                        height: 40
                                        Label:
                                            text: "Victoires"
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR1"])
                                            font_size: min(self.parent.width/2, self.parent.height/2) * 0.5
                                        Label:
                                            id: victories
                                            text: ""
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR1"])
                                            font_size: min(self.parent.width/2, self.parent.height/2) * 0.5
                                    BoxLayout:
                                        orientation:'vertical'
                                        size_hint: 1, 1
                                        canvas.before:
                                            Color:
                                                rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX7"])
                                            RoundedRectangle:
                                                size: self.size
                                                pos: self.pos
                                                radius: [dp(15), dp(15), dp(15), dp(15)]
                                        height: 40
                                        Label:
                                            text: "Defaites"
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR1"])
                                            font_size: min(self.parent.width/2, self.parent.height/2) * 0.5
                                        Label:
                                            id: defeates
                                            text: ""
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR1"])
                                            font_size: min(self.parent.width/2, self.parent.height/2) * 0.5
                                BoxLayout:
                                    orientation:'vertical'
                                    size_hint: 0.5, None
                                    canvas.before:
                                        Color:
                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX7"])
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius: [dp(15), dp(15), dp(15), dp(15)]
                                    pos_hint: {"center_x":0.5}
                                    height: 60
                                    padding: 10
                                    spacing: 10
                                    Label:
                                        text: "Joué dernièrement"
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR1"])
                                        font_size: min(self.parent.width/3, self.parent.height/3) * 0.45
                                    Label:
                                        id: date
                                        text: ""
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR1"])
                                        font_size: min(self.parent.width/3, self.parent.height/3) * 0.45
                                    Label:
                                        id: hour
                                        text: ""
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR1"])
                                        font_size: min(self.parent.width/3, self.parent.height/3) * 0.45
                                BoxLayout:
                                    orientation:'vertical'
                                    size_hint: 1, None
                                    canvas.before:
                                        Color:
                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX8"])
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius: [dp(15), dp(15), dp(15), dp(15)]
                                    pos_hint: {"center_x":0.5}
                                    height: 390
                                    padding: 10
                                    spacing: 10
                                    BoxLayout:
                                        orientation:'horizontal'
                                        BoxLayout:
                                            orientation:'vertical'
                                        Label:
                                            text: "PERFORMANCES SPECIALES"
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                            font_size: min(self.parent.parent.width/13, self.parent.parent.height/13) * 0.7
                                        BoxLayout:
                                            orientation:'vertical'
                                    Label:
                                        text:'Boutons secour utilisés'
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                        font_size: min(self.parent.width/13, self.parent.height/13) * 0.7
                                    Label:
                                        text:'0'
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                        font_size: min(self.parent.width/13, self.parent.height/13) * 0.7
                                    Label:
                                        text:'Points depensés'
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                        font_size: min(self.parent.width/13, self.parent.height/13) * 0.7
                                    Label:
                                        id: used_points
                                        text:''
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                        font_size: min(self.parent.width/13, self.parent.height/13) * 0.7
                                    Label:
                                        text:'meilleure serie de victoires:'
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                        font_size: min(self.parent.width/13, self.parent.height/13) * 0.7
                                    Label:
                                        text:'0'
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                        font_size: min(self.parent.width/13, self.parent.height/13) * 0.7
                                    Label:
                                        text:'Meilleure serie de defaite:'
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                        font_size: min(self.parent.width/13, self.parent.height/13) * 0.7
                                    Label:
                                        text:'0'
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                        font_size: min(self.parent.width/13, self.parent.height/13) * 0.7
                                    Label:
                                        text:'Taux de victoires:'
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                        font_size: min(self.parent.width/13, self.parent.height/13) * 0.7
                                    Label:
                                        text:'0'
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                        font_size: min(self.parent.width/13, self.parent.height/13) * 0.7
                                    Label:
                                        text:'Taux de defaite:'
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                        font_size: min(self.parent.width/13, self.parent.height/13) * 0.7
                                    Label:
                                        text:'0'
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                        font_size: min(self.parent.width/13, self.parent.height/13) * 0.7
                                BoxLayout:
                                    orientation:'horizontal'
                                    size_hint: 1, None
                                    height: 30
                                    BoxLayout:
                                        orientation:'horizontal'
                                        canvas.before:
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos
                                                source: root.get_image_path("br1.png")
                                        size_hint: 0.15, None
                                        height: 30
                                    Label:
                                        text:'REALISATIONS'
                                        color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                        font_size: min(self.parent.width, self.parent.height) * 0.5
                                        bold: True
                                    BoxLayout:
                                        orientation:'vertical'
                                        canvas.before:
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos
                                                source: root.get_image_path("br2.png")
                                        size_hint: 0.15, None
                                        height: 30

                                # Succes box 1
                                BoxLayout:
                                    orientation:'vertical'
                                    size_hint: 1, None
                                    height: 500
                                    size_hint: 0.8, None
                                    pos_hint: {"center_x":0.5}
                                    canvas.before:
                                        Color:
                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX8"])
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius: [dp(10), dp(10), dp(10), dp(10)]
                                    padding: [2, 1, 2, 1]
                                    BoxLayout:
                                        orientation: "vertical"
                                        size_hint: 1, 1
                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                        canvas.before:
                                            Color:
                                                rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                            RoundedRectangle:
                                                size: self.size
                                                pos: self.pos
                                                radius: [dp(10), dp(10), dp(10), dp(10)]
                                        padding: [5, 5, 5, 5]
                                        spacing: 15
                                        BoxLayout:
                                            orientation:'horizontal'
                                            size_hint: 1, None
                                            height: 20
                                            BoxLayout:
                                                orientation:'horizontal'
                                                canvas.before:
                                                    Rectangle:
                                                        size: self.size
                                                        pos: self.pos
                                                        source: root.get_image_path("trophy.png")
                                                size_hint: 0.15, None
                                                height: self.parent.height
                                            Label:
                                                text:'Nombre de victoires'
                                                color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                                font_size: min(self.parent.width, self.parent.height) * 0.6
                                                bold: True
                                            BoxLayout:
                                                orientation:'vertical'
                                                canvas.before:
                                                    Rectangle:
                                                        size: self.size
                                                        pos: self.pos
                                                        source: root.get_image_path("trophy.png")
                                                size_hint: 0.15, None
                                                height: self.parent.height
                                        Label:
                                            text:'Obtenir 50 victoires'
                                            size_hint: 1, None
                                            height: 20
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                            font_size: min(self.width, self.height) * 0.6
                                        BoxLayout:
                                            orientation:'vertical'
                                            size_hint: 0.5, None
                                            pos_hint: {"center_x":0.5}
                                            canvas.before:
                                                Color:
                                                    rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX8"])
                                                RoundedRectangle:
                                                    size: self.size
                                                    pos: self.pos
                                                    radius: [dp(10), dp(10), dp(10), dp(10)]
                                            padding: [1, 1, 1, 1]
                                            BoxLayout:
                                                orientation:'vertical'
                                                size_hint: 1, None
                                                pos_hint: {"center_x":0.5}
                                                canvas.before:
                                                    Color:
                                                        rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                    RoundedRectangle:
                                                        size: self.size
                                                        pos: self.pos
                                                        radius: [dp(10), dp(10), dp(10), dp(10)]
                                                padding: [5, 5, 5, 5]
                                                BoxLayout:
                                                    id: achievement1
                                                    orientation: "vertical"
                                                    size_hint: 1, 1
                                                    pos_hint: {"center_x":0.5, "center_y":0.5}
                                                    path: ""
                                                    canvas.before:
                                                        Color:
                                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                        RoundedRectangle:
                                                            size: self.size
                                                            pos: self.pos
                                                            source: ""#root.get_image_path("RG_1_m_1.png")
                                                            radius: [dp(10), dp(10), dp(10), dp(10)]
                                        Label:
                                            text:'Obtenir 100 victoires'
                                            size_hint: 1, None
                                            height: 20
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                            font_size: min(self.width, self.height) * 0.6
                                        BoxLayout:
                                            orientation:'vertical'
                                            size_hint: 0.5, None
                                            pos_hint: {"center_x":0.5}
                                            canvas.before:
                                                Color:
                                                    rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX8"])
                                                RoundedRectangle:
                                                    size: self.size
                                                    pos: self.pos
                                                    radius: [dp(10), dp(10), dp(10), dp(10)]
                                            padding: [1, 1, 1, 1]
                                            BoxLayout:
                                                orientation:'vertical'
                                                size_hint: 1, None
                                                pos_hint: {"center_x":0.5}
                                                canvas.before:
                                                    Color:
                                                        rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                    RoundedRectangle:
                                                        size: self.size
                                                        pos: self.pos
                                                        radius: [dp(10), dp(10), dp(10), dp(10)]
                                                padding: [5, 5, 5, 5]
                                                BoxLayout:
                                                    id: achievement2
                                                    orientation: "vertical"
                                                    size_hint: 1, 1
                                                    pos_hint: {"center_x":0.5, "center_y":0.5}
                                                    path: ""
                                                    canvas.before:
                                                        Color:
                                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                        RoundedRectangle:
                                                            size: self.size
                                                            pos: self.pos
                                                            source: ""#root.get_image_path("RG_1_m_2.png")
                                                            radius: [dp(10), dp(10), dp(10), dp(10)]
                                        Label:
                                            text:'Obtenir 200 victoires'
                                            size_hint: 1, None
                                            height: 20
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                            font_size: min(self.width, self.height) * 0.6
                                        BoxLayout:
                                            orientation:'vertical'
                                            size_hint: 0.5, None
                                            pos_hint: {"center_x":0.5}
                                            canvas.before:
                                                Color:
                                                    rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX8"])
                                                RoundedRectangle:
                                                    size: self.size
                                                    pos: self.pos
                                                    radius: [dp(10), dp(10), dp(10), dp(10)]
                                            padding: [1, 1, 1, 1]
                                            BoxLayout:
                                                orientation:'vertical'
                                                size_hint: 1, None
                                                pos_hint: {"center_x":0.5}
                                                canvas.before:
                                                    Color:
                                                        rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                    RoundedRectangle:
                                                        size: self.size
                                                        pos: self.pos
                                                        radius: [dp(10), dp(10), dp(10), dp(10)]
                                                padding: [5, 5, 5, 5]
                                                BoxLayout:
                                                    id: achievement3
                                                    orientation: "vertical"
                                                    size_hint: 1, 1
                                                    pos_hint: {"center_x":0.5, "center_y":0.5}
                                                    path: ""
                                                    canvas.before:
                                                        Color:
                                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                        RoundedRectangle:
                                                            size: self.size
                                                            pos: self.pos
                                                            source: ""#root.get_image_path("RG_1_m_3.png")
                                                            radius: [dp(10), dp(10), dp(10), dp(10)]
                                
                                # Succes box 2
                                BoxLayout:
                                    orientation:'vertical'
                                    size_hint: 1, None
                                    height: 500
                                    size_hint: 0.8, None
                                    pos_hint: {"center_x":0.5}
                                    canvas.before:
                                        Color:
                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX8"])
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius: [dp(10), dp(10), dp(10), dp(10)]
                                    padding: [2, 1, 2, 1]
                                    BoxLayout:
                                        orientation: "vertical"
                                        size_hint: 1, 1
                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                        canvas.before:
                                            Color:
                                                rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                            RoundedRectangle:
                                                size: self.size
                                                pos: self.pos
                                                radius: [dp(10), dp(10), dp(10), dp(10)]
                                        padding: [5, 5, 5, 5]
                                        spacing: 15
                                        BoxLayout:
                                            orientation:'horizontal'
                                            size_hint: 1, None
                                            height: 20
                                            BoxLayout:
                                                orientation:'horizontal'
                                                canvas.before:
                                                    Rectangle:
                                                        size: self.size
                                                        pos: self.pos
                                                        source: root.get_image_path("perfect.png")
                                                size_hint: 0.15, None
                                                height: self.parent.height
                                            Label:
                                                text:'Score pafait'
                                                color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                                font_size: min(self.parent.width, self.parent.height) * 0.6
                                                bold: True
                                            BoxLayout:
                                                orientation:'vertical'
                                                canvas.before:
                                                    Rectangle:
                                                        size: self.size
                                                        pos: self.pos
                                                        source: root.get_image_path("perfect.png")
                                                size_hint: 0.15, None
                                                height: self.parent.height
                                        Label:
                                            text:'Gagner 5x sans pedre de plume'
                                            size_hint: 1, None
                                            height: 20
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                            font_size: min(self.width, self.height) * 0.5
                                        BoxLayout:
                                            orientation:'vertical'
                                            size_hint: 0.5, None
                                            pos_hint: {"center_x":0.5}
                                            canvas.before:
                                                Color:
                                                    rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX8"])
                                                RoundedRectangle:
                                                    size: self.size
                                                    pos: self.pos
                                                    radius: [dp(10), dp(10), dp(10), dp(10)]
                                            padding: [1, 1, 1, 1]
                                            BoxLayout:
                                                orientation:'vertical'
                                                size_hint: 1, None
                                                pos_hint: {"center_x":0.5}
                                                canvas.before:
                                                    Color:
                                                        rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                    RoundedRectangle:
                                                        size: self.size
                                                        pos: self.pos
                                                        radius: [dp(10), dp(10), dp(10), dp(10)]
                                                padding: [5, 5, 5, 5]
                                                BoxLayout:
                                                    id: achievement4
                                                    orientation: "vertical"
                                                    size_hint: 1, 1
                                                    pos_hint: {"center_x":0.5, "center_y":0.5}
                                                    path: ""
                                                    canvas.before:
                                                        Color:
                                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                        RoundedRectangle:
                                                            size: self.size
                                                            pos: self.pos
                                                            source: ""#root.get_image_path("RG_2_m_1.png")
                                                            radius: [dp(10), dp(10), dp(10), dp(10)]
                                        Label:
                                            text:'Gagner 10x sans pedre de plume'
                                            size_hint: 1, None
                                            height: 20
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                            font_size: min(self.width, self.height) * 0.5
                                        BoxLayout:
                                            orientation:'vertical'
                                            size_hint: 0.5, None
                                            pos_hint: {"center_x":0.5}
                                            canvas.before:
                                                Color:
                                                    rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX8"])
                                                RoundedRectangle:
                                                    size: self.size
                                                    pos: self.pos
                                                    radius: [dp(10), dp(10), dp(10), dp(10)]
                                            padding: [1, 1, 1, 1]
                                            BoxLayout:
                                                orientation:'vertical'
                                                size_hint: 1, None
                                                pos_hint: {"center_x":0.5}
                                                canvas.before:
                                                    Color:
                                                        rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                    RoundedRectangle:
                                                        size: self.size
                                                        pos: self.pos
                                                        radius: [dp(10), dp(10), dp(10), dp(10)]
                                                padding: [5, 5, 5, 5]
                                                BoxLayout:
                                                    id: achievement5
                                                    orientation: "vertical"
                                                    size_hint: 1, 1
                                                    pos_hint: {"center_x":0.5, "center_y":0.5}
                                                    path: ""
                                                    canvas.before:
                                                        Color:
                                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                        RoundedRectangle:
                                                            size: self.size
                                                            pos: self.pos
                                                            source: ""#root.get_image_path("RG_2_m_2.png")
                                                            radius: [dp(10), dp(10), dp(10), dp(10)]
                                        Label:
                                            text:'Gagner 20x sans pedre de plume'
                                            size_hint: 1, None
                                            height: 20
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                            font_size: min(self.width, self.height) * 0.5
                                        BoxLayout:
                                            orientation:'vertical'
                                            size_hint: 0.5, None
                                            pos_hint: {"center_x":0.5}
                                            canvas.before:
                                                Color:
                                                    rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX8"])
                                                RoundedRectangle:
                                                    size: self.size
                                                    pos: self.pos
                                                    radius: [dp(10), dp(10), dp(10), dp(10)]
                                            padding: [1, 1, 1, 1]
                                            BoxLayout:
                                                orientation:'vertical'
                                                size_hint: 1, None
                                                pos_hint: {"center_x":0.5}
                                                canvas.before:
                                                    Color:
                                                        rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                    RoundedRectangle:
                                                        size: self.size
                                                        pos: self.pos
                                                        radius: [dp(10), dp(10), dp(10), dp(10)]
                                                padding: [5, 5, 5, 5]
                                                BoxLayout:
                                                    id: achievement6
                                                    orientation: "vertical"
                                                    size_hint: 1, 1
                                                    pos_hint: {"center_x":0.5, "center_y":0.5}
                                                    path: ""
                                                    canvas.before:
                                                        Color:
                                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                        RoundedRectangle:
                                                            size: self.size
                                                            pos: self.pos
                                                            source: ""#root.get_image_path("RG_2_m_3.png")
                                                            radius: [dp(10), dp(10), dp(10), dp(10)]

                                # Succes box 3
                                BoxLayout:
                                    orientation:'vertical'
                                    size_hint: 1, None
                                    height: 500
                                    size_hint: 0.8, None
                                    pos_hint: {"center_x":0.5}
                                    canvas.before:
                                        Color:
                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX8"])
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius: [dp(10), dp(10), dp(10), dp(10)]
                                    padding: [2, 1, 2, 1]
                                    BoxLayout:
                                        orientation: "vertical"
                                        size_hint: 1, 1
                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                        canvas.before:
                                            Color:
                                                rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                            RoundedRectangle:
                                                size: self.size
                                                pos: self.pos
                                                radius: [dp(10), dp(10), dp(10), dp(10)]
                                        padding: [5, 5, 5, 5]
                                        spacing: 15
                                        BoxLayout:
                                            orientation:'horizontal'
                                            size_hint: 1, None
                                            height: 20
                                            BoxLayout:
                                                orientation:'horizontal'
                                                canvas.before:
                                                    Rectangle:
                                                        size: self.size
                                                        pos: self.pos
                                                        source: root.get_image_path("death_head.png")
                                                size_hint: 0.15, None
                                                height: self.parent.height
                                            Label:
                                                text:'Frontière victoire-défaite'
                                                color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                                font_size: min(self.parent.width, self.parent.height) * 0.5
                                                bold: True
                                            BoxLayout:
                                                orientation:'vertical'
                                                canvas.before:
                                                    Rectangle:
                                                        size: self.size
                                                        pos: self.pos
                                                        source: root.get_image_path("death_head.png")
                                                size_hint: 0.15, None
                                                height: self.parent.height
                                        Label:
                                            text:'Gagner 5x avec une plume restante'
                                            size_hint: 1, None
                                            height: 20
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                            font_size: min(self.width, self.height) * 0.5
                                        BoxLayout:
                                            orientation:'vertical'
                                            size_hint: 0.5, None
                                            pos_hint: {"center_x":0.5}
                                            canvas.before:
                                                Color:
                                                    rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX8"])
                                                RoundedRectangle:
                                                    size: self.size
                                                    pos: self.pos
                                                    radius: [dp(10), dp(10), dp(10), dp(10)]
                                            padding: [1, 1, 1, 1]
                                            BoxLayout:
                                                orientation:'vertical'
                                                size_hint: 1, None
                                                pos_hint: {"center_x":0.5}
                                                canvas.before:
                                                    Color:
                                                        rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                    RoundedRectangle:
                                                        size: self.size
                                                        pos: self.pos
                                                        radius: [dp(10), dp(10), dp(10), dp(10)]
                                                padding: [5, 5, 5, 5]
                                                BoxLayout:
                                                    id: achievement7
                                                    orientation: "vertical"
                                                    size_hint: 1, 1
                                                    pos_hint: {"center_x":0.5, "center_y":0.5}
                                                    path: ""
                                                    canvas.before:
                                                        Color:
                                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                        RoundedRectangle:
                                                            size: self.size
                                                            pos: self.pos
                                                            source: ""#root.get_image_path("RG_3_m_1.png")
                                                            radius: [dp(10), dp(10), dp(10), dp(10)]
                                        Label:
                                            text:'Gagner 10x avec une plume restante'
                                            size_hint: 1, None
                                            height: 20
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                            font_size: min(self.width, self.height) * 0.5
                                        BoxLayout:
                                            orientation:'vertical'
                                            size_hint: 0.5, None
                                            pos_hint: {"center_x":0.5}
                                            canvas.before:
                                                Color:
                                                    rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX8"])
                                                RoundedRectangle:
                                                    size: self.size
                                                    pos: self.pos
                                                    radius: [dp(10), dp(10), dp(10), dp(10)]
                                            padding: [1, 1, 1, 1]
                                            BoxLayout:
                                                orientation:'vertical'
                                                size_hint: 1, None
                                                pos_hint: {"center_x":0.5}
                                                canvas.before:
                                                    Color:
                                                        rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                    RoundedRectangle:
                                                        size: self.size
                                                        pos: self.pos
                                                        radius: [dp(10), dp(10), dp(10), dp(10)]
                                                padding: [5, 5, 5, 5]
                                                BoxLayout:
                                                    id: achievement8
                                                    orientation: "vertical"
                                                    size_hint: 1, 1
                                                    pos_hint: {"center_x":0.5, "center_y":0.5}
                                                    path: ""
                                                    canvas.before:
                                                        Color:
                                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                        RoundedRectangle:
                                                            size: self.size
                                                            pos: self.pos
                                                            source: ""#root.get_image_path("RG_3_m_2.png")
                                                            radius: [dp(10), dp(10), dp(10), dp(10)]
                                        Label:
                                            text:'Gagner 20x avec une plume restante'
                                            size_hint: 1, None
                                            height: 20
                                            color: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["TEXT"]["COLOR2"])
                                            font_size: min(self.width, self.height) * 0.5
                                        BoxLayout:
                                            orientation:'vertical'
                                            size_hint: 0.5, None
                                            pos_hint: {"center_x":0.5}
                                            canvas.before:
                                                Color:
                                                    rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX8"])
                                                RoundedRectangle:
                                                    size: self.size
                                                    pos: self.pos
                                                    radius: [dp(10), dp(10), dp(10), dp(10)]
                                            padding: [1, 1, 1, 1]
                                            BoxLayout:
                                                orientation:'vertical'
                                                size_hint: 1, None
                                                pos_hint: {"center_x":0.5}
                                                canvas.before:
                                                    Color:
                                                        rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                    RoundedRectangle:
                                                        size: self.size
                                                        pos: self.pos
                                                        radius: [dp(10), dp(10), dp(10), dp(10)]
                                                padding: [5, 5, 5, 5]
                                                BoxLayout:
                                                    id: achievement9
                                                    orientation: "vertical"
                                                    size_hint: 1, 1
                                                    pos_hint: {"center_x":0.5, "center_y":0.5}
                                                    path: ""
                                                    canvas.before:
                                                        Color:
                                                            rgb: hex(root.get_colors()["PLAYER_DATA_SCREEN"]["BACKGROUND"]["DATA_BOX6"])
                                                        RoundedRectangle:
                                                            size: self.size
                                                            pos: self.pos
                                                            source: ""#root.get_image_path("RG_3_m_3.png")
                                                            radius: [dp(10), dp(10), dp(10), dp(10)]


                            

<KeyBordCraftingLab>:
    canvas.before:
        Color:
            rgb: hex("#FFFFFF")
        Rectangle:
            size: self.size
            pos: self.pos
    CustomTextInput:
        id: note
        size_hint: 0.7, 0.8
        pos_hint: {"center_x":0.5, "center_y":0.5}
        bg_color: hex(root.get_colors()["DEFEATE_SCREEN"]["BACKGROUND"]["BOX"]["COLOR2"])
        multiline: True
        default_value: 0.05
    Button:
        text:'Reset'
        color: 1, 0, 0, 1
        on_release: root.reset_sentence()
        size_hint: 0.08, 0.05
        pos_hint: {"x":0.9, "y":0.9}



<CustomButton>:
    id: self.id
    background_normal: ""
    background_activate: ""
    background_color: 0, 0, 0, 0
    
    canvas.before:
        Color:
            rgb: self.bg_color
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: self.radius

<CustomTextInput>:
    custom_text_input: custom_text_input
    BoxLayout:
        orientation: "horizontal"
        size: self.size
        pos_hint: {"center_x":0.5}
        padding: dp(3)
        canvas.before:
            Color:
                rgb:  self.parent.bg_color
            RoundedRectangle:
                size: self.size
                pos: self.pos
                radius: self.parent.radius
        BoxLayout:
            orientation: "horizontal"
            TextInput:
                id: custom_text_input
                text: ""
                readonly: True
                background_normal: ""
                background_activate: ""
                background_color: 0, 0, 0, 0
                foreground_color: self.parent.parent.parent.text_color
                halign: "center"#self.parent.parent.parent.halign
                valign: "middle"#self.parent.parent.parent.valign
                font_size: min(self.width, self.height) * self.parent.parent.parent.default_value
                bold: True
                multiline: self.parent.parent.parent.multiline

<FeatherFrame>:
    orientation:'vertical'
    canvas.before:
        Color:
            rgb: self.bg_color
        Rectangle:
            size: self.size
            pos: self.pos
            source: self.image_path
<CustomKeyBoard>:
    a0_button: a0_button
    a1_button: a1_button
    a2_button: a2_button
    e0_button: e0_button
    e1_button: e1_button
    e2_button: e2_button
    u0_button: u0_button
    i0_button: i0_button
    i1_button: i1_button
    o0_button: o0_button
    a3_button: a3_button
    z_button: z_button
    e3_button: e3_button
    r_button: r_button
    t_button: t_button
    y_button: y_button
    u_button: u_button
    i2_button: i2_button
    o1_button: o1_button
    p_button: p_button
    q_button: q_button
    s_button: s_button
    d_button: d_button
    f_button: f_button
    g_button: g_button
    h_button: h_button
    j_button: j_button
    k_button: k_button
    l_button: l_button
    m_button: m_button
    w_button: w_button
    x_button: x_button
    c_button: c_button
    v_button: v_button
    b_button: b_button
    n_button: n_button
    
    id: keyboard
    canvas.before:
        Color:
            rgb: hex(self.bg_color)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: self.radius
    BoxLayout:
        orientation: "vertical"
        size_hint: 0.95, 0.95
        pos_hint: {"center_x": 0.5, "center_y":0.5}
        spacing: 5
        BoxLayout:
            id: lin1
            orientation: "horizontal"
            spacing: 5
            pos_hint: {"center_x":0.5, "center_y":0.5}
            size_hint: 1, 1
            CustomButton:
                id: a0_button
                text: "à"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: a1_button
                text: "â"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: a2_button
                text: "ä"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: e0_button
                text: "ê"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: e1_button
                text: "é"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: e2_button
                text: "è"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: u0_button
                text: "û"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: i0_button
                text: "ï"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: i1_button
                text: "î"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: o0_button
                text: "ô"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
        BoxLayout:
            id: lin2
            orientation: "horizontal"
            spacing: 5
            pos_hint: {"center_x":0.5, "center_y":0.5}
            size_hint: 1, 1
            CustomButton:
                id: a3_button
                text: "a"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: z_button
                text: "z"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: e3_button
                text: "e"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: r_button
                text: "r"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: t_button
                text: "t"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: y_button
                text: "y"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: u_button
                text: "u"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: i2_button
                text: "i"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: o1_button
                text: "o"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: p_button
                text: "p"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
        BoxLayout:
            id: lin3
            orientation: "horizontal"
            spacing: 5
            pos_hint: {"center_x":0.5, "center_y":0.5}
            size_hint: 1, 1
            CustomButton:
                id: q_button
                text: "q"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: s_button
                text: "s"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: d_button
                text: "d"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: f_button
                text: "f"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: g_button
                text: "g"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: h_button
                text: "h"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: j_button
                text: "j"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: k_button
                text: "k"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: l_button
                text: "l"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
            CustomButton:
                id: m_button
                text: "m"

                font_size: min(self.width, self.height) * 0.8
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press(self.text)
                bold: True
        BoxLayout:
            id: lin4
            orientation: "horizontal"
            spacing: 5
            pos_hint: {"center_x":0.5, "center_y":0.5}
            size_hint: 1, 1
            CustomButton:
                id: up_button
                text: "^"
                size_hint: 0.2, 1
                keyboard: root

                font_size: min(self.width, self.height) * 0.5
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.keyboard.grown_or_down()
                bold: True
            BoxLayout:
                orientation: "horizontal"
                spacing: 10
                CustomButton:
                    id: w_button
                    text: "w"

                    font_size: min(self.width, self.height) * 0.8
                    radius: [25]
                    bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                    on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]   ["ON_RELEASE"])
                    on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"] ["ON_PRESS"]); self.parent.parent.parent.parent.on_key_press(self.text)
                    bold: True
                CustomButton:
                    id: x_button
                    text: "x"

                    font_size: min(self.width, self.height) * 0.8
                    radius: [25]
                    bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                    on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]   ["ON_RELEASE"])
                    on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"] ["ON_PRESS"]); self.parent.parent.parent.parent.on_key_press(self.text)
                    bold: True
                CustomButton:
                    id: c_button
                    text: "c"

                    font_size: min(self.width, self.height) * 0.8
                    radius: [25]
                    bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                    on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]   ["ON_RELEASE"])
                    on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"] ["ON_PRESS"]); self.parent.parent.parent.parent.on_key_press(self.text)
                    bold: True
                CustomButton:
                    id: v_button
                    text: "v"

                    font_size: min(self.width, self.height) * 0.8
                    radius: [25]
                    bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                    on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]   ["ON_RELEASE"])
                    on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"] ["ON_PRESS"]); self.parent.parent.parent.parent.on_key_press(self.text)
                    bold: True
                CustomButton:
                    id: b_button
                    text: "b"

                    font_size: min(self.width, self.height) * 0.8
                    radius: [25]
                    bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                    on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]   ["ON_RELEASE"])
                    on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"] ["ON_PRESS"]); self.parent.parent.parent.parent.on_key_press(self.text)
                    bold: True
                CustomButton:
                    id: n_button
                    text: "n"

                    font_size: min(self.width, self.height) * 0.8
                    radius: [25]
                    bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                    on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]   ["ON_RELEASE"])
                    on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"] ["ON_PRESS"]); self.parent.parent.parent.parent.on_key_press(self.text)
                    bold: True
                CustomButton:
                    id: apostrophe_button
                    text: "'"

                    font_size: min(self.width, self.height) * 0.8
                    radius: [25]
                    bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                    on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]   ["ON_RELEASE"])
                    on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"] ["ON_PRESS"])
                    bold: True
            CustomButton:
                id: del_button
                text: "<--"
                size_hint: 0.2, 1

                font_size: min(self.width, self.height) * 0.5
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.parent.parent.on_key_press("")
                bold: True
        BoxLayout:
            id: lin5
            orientation: "horizontal"
            spacing: 5
            pos_hint: {"center_x":0.5, "center_y":0.5}
            size_hint: 1, 1
            CustomButton:
                id: keyboader_manager1
                text: "?123"
                size_hint:0.2, 1

                font_size: min(self.width, self.height) * 0.5
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); self.parent.grown_or_down()
                bold: True
            CustomButton:
                id: dot_button
                text: ","
                size_hint: 0.11111, 1

                font_size: min(self.width, self.height) * 0.5
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                bold: True
            CustomButton:
                id: spacer_button
                text: "Espace"
                size_hint: 0.5, 1

                font_size: min(self.width, self.height) * 0.5
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                bold: True
            CustomButton:
                id: toogle_keyborad_color_button
                text: "<->"
                size_hint: 0.095, 1

                font_size: min(self.width, self.height) * 0.5
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                bold: True
            CustomButton:
                id: check_button
                text: "0k"
                size_hint: 0.095, 1

                font_size: min(self.width, self.height) * 0.5
                radius: [25]
                bg_color: hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"])
                on_press: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_RELEASE"])
                on_release: self.bg_color=hex(root.get_colors()["CUSTOM_KEYBOARD"]["BACKGROUND"]["BUTTONS"]["ON_PRESS"]); root.validate_letter()
                bold: True
    

<Manager>:
    id: screen_manager

    welcome_screen: welcome_screen
    level_selecting_screen: level_selecting_screen
    stat_level_selecting: stat_level_selecting
    player_data_screen: player_data_screen
    game_view: game_view
    defeate_screen: defeate_screen

    WelcomeScreen:
        id: welcome_screen
        name: "welcome_screen"
        manager: screen_manager

    LevelSelectingScreen:
        id: level_selecting_screen
        name: "level_selecting_screen"
        manager: screen_manager
    
    StatLevelSelectingScreen:
        id: stat_level_selecting
        name: "stat_level_selecting"
        manager: screen_manager

    PlayerDataScreen:
        id: player_data_screen
        name: "player_data"
        manager: screen_manager

    GameView:
        id: game_view
        name: "game_view"
        manager: screen_manager

    KeyBordCraftingLab:
        id: keyboard_crafting_lab
        name: "keyboard_crafting_lab"
        manager: screen_manager

    DefeateScreen:
        id: defeate_screen
        name: "defeate_screen"
        manager: screen_manager

    VictoryScreen:
        id: victory_screen
        name: "victory_screen"
        manager: screen_manager

    CreateAccountScreen:
        id: create_account_screen
        name: "create_account_screen"
        manager: screen_manager
